repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.12
        files: '^.*\.py$'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        args: [--fix]
        language_version: python3.12
        files: '^.*\.py$'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        language: system
        entry: mypy
        args:
          - --strict
          - --warn-unused-ignores
          - --explicit-package-bases
        files: '^.*\.py$'
        exclude: ^tests/

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system         # run inside the same env
        entry: pytest
        pass_filenames: false
