repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3
        files: '^.*\.py$'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        args: [--fix]
        language_version: python3
        files: '^.*\.py$'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        language: system
        args:
          - --strict
          - --warn-unused-ignores
          - --explicit-package-bases
        files: '^.*\.py$'
